# Build river and run the test suite with xwayland enabled every time a commit
# is pushed to master or a pull request is opened against master.

on: [push, pull_request]

name: Archliunx + Xwayland

jobs:
  build:
    name: Archliunx + Xwayland
    runs-on: ubuntu-latest
    container: archlinux:latest

    steps:
      - name: Install Dependencies
        run: |
          pacman -Syu --noconfirm zig wayland-protocols wlroots pkgconf

      - name: Checkout Code
        uses: actions/checkout@master

      - name: build
        run: |
          zig build -Dxwayland=true

      - name: test
        run: |
          zig build -Dxwayland=true test

      - name: zig fmt
        run: |
          find . -path ./zig-cache -prune -o -name "*.zig" -exec zig fmt --check {} ";"
